---
# Tasks performed by default when this role is included.
# Reference: include_tasks module (Ansible builtin collection).
- name: Include Clone Task
  ansible.builtin.include_tasks:
    file: git_clone.yml
...
